// <auto-generated />
using System;
using CowManagerApp.MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CowManagerApp.MVC.Migrations
{
    [DbContext(typeof(CowManagerContext))]
    [Migration("20240813065034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CowManagerApp.MVC.Models.Cow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .IsFixedLength();

                    b.Property<int?>("Idherd")
                        .HasColumnType("int")
                        .HasColumnName("IDHerd");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Idherd");

                    b.ToTable("Cow", (string)null);
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .IsFixedLength();

                    b.Property<int>("Idcow")
                        .HasColumnType("int")
                        .HasColumnName("IDCow");

                    b.Property<int>("Iddisease")
                        .HasColumnType("int")
                        .HasColumnName("IDDisease");

                    b.Property<string>("NameOfDisease")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Idcow");

                    b.HasIndex("Iddisease");

                    b.ToTable("Diagnosis", (string)null);
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Disease", (string)null);
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Herd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Herd", (string)null);
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Medicine", (string)null);
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nchar(200)")
                        .IsFixedLength();

                    b.Property<int>("Idcow")
                        .HasColumnType("int")
                        .HasColumnName("IDCow");

                    b.Property<int>("Iddiagnosis")
                        .HasColumnType("int")
                        .HasColumnName("IDDiagnosis");

                    b.Property<int>("Idmedicine")
                        .HasColumnType("int")
                        .HasColumnName("IDMedicine");

                    b.Property<string>("NameOfMedicine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Idcow");

                    b.HasIndex("Iddiagnosis");

                    b.HasIndex("Idmedicine");

                    b.ToTable("Treatment", (string)null);
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Cow", b =>
                {
                    b.HasOne("CowManagerApp.MVC.Models.Herd", "IdherdNavigation")
                        .WithMany("Cows")
                        .HasForeignKey("Idherd")
                        .HasConstraintName("FK_Cow_Herd");

                    b.Navigation("IdherdNavigation");
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Diagnosis", b =>
                {
                    b.HasOne("CowManagerApp.MVC.Models.Cow", "IdcowNavigation")
                        .WithMany()
                        .HasForeignKey("Idcow")
                        .IsRequired()
                        .HasConstraintName("FK_Diagnosis_Cow");

                    b.HasOne("CowManagerApp.MVC.Models.Disease", "IddiseaseNavigation")
                        .WithMany()
                        .HasForeignKey("Iddisease")
                        .IsRequired()
                        .HasConstraintName("FK_Diagnosis_Disease");

                    b.Navigation("IdcowNavigation");

                    b.Navigation("IddiseaseNavigation");
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Treatment", b =>
                {
                    b.HasOne("CowManagerApp.MVC.Models.Cow", "IdcowNavigation")
                        .WithMany()
                        .HasForeignKey("Idcow")
                        .IsRequired()
                        .HasConstraintName("FK_Treatment_Cow");

                    b.HasOne("CowManagerApp.MVC.Models.Diagnosis", "IddiagnosisNavigation")
                        .WithMany()
                        .HasForeignKey("Iddiagnosis")
                        .IsRequired()
                        .HasConstraintName("FK_Treatment_Diagnosis");

                    b.HasOne("CowManagerApp.MVC.Models.Medicine", "IdmedicineNavigation")
                        .WithMany()
                        .HasForeignKey("Idmedicine")
                        .IsRequired()
                        .HasConstraintName("FK_Treatment_Medicine");

                    b.Navigation("IdcowNavigation");

                    b.Navigation("IddiagnosisNavigation");

                    b.Navigation("IdmedicineNavigation");
                });

            modelBuilder.Entity("CowManagerApp.MVC.Models.Herd", b =>
                {
                    b.Navigation("Cows");
                });
#pragma warning restore 612, 618
        }
    }
}
